package com.ciq.queries;

public interface EmployeeQueries {

	String EMP_INSERT_QUERY = "INSERT INTO EMPLOYEE_TAB(EID,ENAME,ESAL) VALUES(?,?,?)";
	String EMP_UPDATE_QUERY = "UPDATE EMPLOYEE_TAB SET ENAME = ?, ESAL = ? WHERE EID = ?";
	String EMP_DELETE_BY_ID_QUERY = "DELETE FROM EMPLOYEE_TAB WHERE EID = ?";
	String EMP_FIND_BY_ID_QUERY = "SELECT * FROM EMPLOYEE_TAB WHERE EID = ?";
	String EMP_FIND_ALL_QUERY = "SELECT * FROM EMPLOYEE_TAB";

}
